# -*- coding: utf-8 -*-
"""BETANO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ZTzAFdPnndMi3lMA6Ft9009A6ujGdm1
"""

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

plan = gc.open('Betfair')

page = plan.sheet1

rows = page.get_all_values()
print(rows)

import pandas as pd
pd.DataFrame.from_records(rows)

from bs4 import BeautifulSoup
import re

import requests
url = ("https://www.betfair.com/sport/virtuals-results?sport=SOCCER&day=2022-01-31")
r = requests.get(url)

bs = BeautifulSoup(r.text, 'html.parser')

times = bs.find_all('div')

for i in times:
    print(i.text)



import datetime

hoje = datetime.datetime.now()
hoje = str(hoje)
conteudo = [url, times, hoje ]

registros = worksheet.range('A2:D2')

for i in range(0, len(registros)):
 registros[i].value = conteudo[i]

worksheet.update_cells(registros)