# -*- coding: utf-8 -*-
"""Betfair.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V93vrspsPE9niHMkPjQckXo3SewW_thE
"""

import requests
from bs4 import BeautifulSoup

url = ("https://www.betfair.com/sport/virtuals-results?sport=SOCCER&day=2022-01-31")
page = requests.get(url)

bs = BeautifulSoup(page.text, 'html.parser')

titulo = bs.find_all('div', attrs={"class": "result-header"})

from google.colab import auth
auth.authenticate_user()

import gspread
from oauth2client.client import GoogleCredentials

gc = gspread.authorize(GoogleCredentials.get_application_default())

import datetime

hoje = datetime.datetime.now()
hoje = str(hoje)

registros = worksheet.range('A2:D2')

for i in range(0, len(registros)):
  registros[i].value = times[i]

worksheet.update_cells(registros)